module.exports = {
    'a':{
        vowel:true,
        children:{
            'b':{
                vowel:false,
                children:{
                    'd':{
                        vowel:false,
                    },
                    'e':{
                        vowel:true,
                    },
                    'f':{
                        vowel:false,
                    },
                    'g':{
                        vowel:false,
                    },
                }
            },
            'c':{
                vowel:true,
                children:{
                    'h':{
                        vowel:false,
                
                    },
                    'i':{
                        vowel:true,
                    },
                    'j':{
                        vowel:false,
                    },
                    'k':{
                        vowel:false,
                    }
                }
            }
        }
        
    }
}
